repos:
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        description: Lint using flake8.
        entry: pipenv run flake8
        language: python
        types: [python]
        require_serial: true
