version: "3.7"
services:
  fbla-quiz:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgres://fbla_quiz:fbla_quiz@postgres:5432/fbla_quiz
      SECRET_KEY: not-suitable-for-production
      DEBUG: 1
    depends_on:
      - postgres
    volumes:
      - ./:/app/:ro
      - ./static/:/app/static/

  postgres:
    image: postgres:12
    expose:
      - 5432
    environment:
      POSTGRES_DB: fbla_quiz
      POSTGRES_USER: fbla_quiz
      POSTGRES_PASSWORD: fbla_quiz
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data

volumes:
  postgres_data:
  static:
