# Generated by Django 3.1.3 on 2020-12-01 03:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceQuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question of the entry.', max_length=4096)),
                ('answer', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='The answers to the question.', size=None)),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='All possible choices for a question, including the answers themselves.', size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MultipleChoiceQuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question of the entry.', max_length=4096)),
                ('answer', models.CharField(help_text='The answer to the question.', max_length=256)),
                ('answer_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), help_text='All possible choices for a question, including the answer itself.', size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShortAnswerQuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question of the entry.', max_length=4096)),
                ('answer', models.CharField(help_text='The answer to the question.', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrueFalseQuizEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The question of the entry.', max_length=4096)),
                ('answer', models.BooleanField(help_text='The answer to the question.')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
